### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by Suraj1089** [pydantic/pydantic-ai#135]
I am running [this example](https://ai.pydantic.dev/agents/#running-agents:~:text=Chat%20History.-,Runs%20vs.%20Conversations,-An%20agent%20run) from the documentation 
```python
from pydantic_ai import Agent

agent = Agent('openai:gpt-4o')

# First run
result1 = agent.run_sync('Who was Albert Einstein?')
print(result1.data)
#> Albert Einstein was a German-born theoretical physicist.

# Second run, passing previous messages
result2 = agent.run_sync(
    'What was his most famous equation?',
    message_history=result1.new_messages(),  
)
print(result2.data)
#> Albert Einstein's most famous equation is (E = mc^2).
```
getting the below error with `gemini-1.5-flash` model.  - 
```bash
Albert Einstein (1879-1955) was a German-born theoretical physicist widely regarded as one of the most influential scientists of all time. He is best known for his theory of relativity, which fundamentally changed our understanding of space, time, gravity, and the universe.  His work also included significant contributions to the development of quantum theory and statistical mechanics.  His mass–energy equivalence formula,  E=mc², is arguably the most famous equation in physics. Beyond his scientific achievements, Einstein was a humanist and pacifist, known for his advocacy of social justice and world peace.

Traceback (most recent call last):
  File "/Users/surajpisal/personal/ai-course/main.py", line 12, in <module>
    result2 = agent.run_sync(
              ^^^^^^^^^^^^^^^
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 220, in run_sync
    return asyncio.run(self.run(user_prompt, message_history=message_history, model=model, deps=deps))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 172, in run
    model_response, request_cost = await agent_model.request(messages)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/pydantic_ai/models/gemini.py", line 167, in request
    async with self._make_request(messages, False) as http_response:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/pydantic_ai/models/gemini.py", line 205, in _make_request
    async with self.http_client.stream('POST', url, content=request_json, headers=headers) as r:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1585, in stream
    response = await self.send(
               ^^^^^^^^^^^^^^^^
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1631, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1659, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1696, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1732, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/httpcore/_async/http11.py", line 135, in handle_async_request
    await self._response_closed()
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/httpcore/_async/http11.py", line 250, in _response_closed
    await self.aclose()
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/httpcore/_async/http11.py", line 258, in aclose
    await self._network_stream.aclose()
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 53, in aclose
    await self._stream.aclose()
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/anyio/streams/tls.py", line 201, in aclose
    await self.transport_stream.aclose()
  File "/Users/surajpisal/personal/ai-course/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 1287, in aclose
    self._transport.close()
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", line 1210, in close
    super().close()
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", line 875, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
    self._check_closed()
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by samuelcolvin** [comment]
Duplicate of #114, already fixed on main, I'll make a new release today.
