### ISSUE TITLE
Empty Tools Array Error when using Azure OpenAI

### ISSUE THREAD

**Issue by slavashvets** [pydantic/pydantic-ai#155]
When using Azure OpenAI, the library fails with a 400 error due to an empty tools array being sent in the API request. While the default Azure OpenAI Python SDK example works correctly, the equivalent code using `pydantic-ai` fails.

## Reproduction Steps
Run the following code:

```python
import asyncio
from openai import AsyncAzureOpenAI
from pydantic_ai import Agent
from pydantic_ai.models.openai import OpenAIModel

client = AsyncAzureOpenAI(
    azure_endpoint="xxx",
    api_version="2024-06-01",
    api_key="xxx",
    azure_deployment="gpt-4o",
)

model = OpenAIModel("gpt-4o-2024-08-06", openai_client=client)
agent = Agent(model)

async def main():
    response = await agent.run("Hello, how are you?")
    print(response)

asyncio.run(main())
```

## Expected Behavior
The code should execute successfully and return a response object with the model's reply:

```python
RunResult(response="Hello! I'm just a computer program, so I don't have feelings, but I'm here and ready to help you. How can I assist you today?", message_history=[UserPrompt(content='Hello, how are you?', timestamp=datetime.datetime(2024, 12, 6, 13, 27, 22, 781245, tzinfo=datetime.timezone.utc), role='user'), LLMResponse(content="Hello! I'm just a computer program, so I don't have feelings, but I'm here and ready to help you. How can I assist you today?", timestamp=datetime.datetime(2024, 12, 6, 13, 27, 23, tzinfo=datetime.timezone.utc), role='llm-response')], cost=Cost(request_tokens=13, response_tokens=30, total_tokens=43, details=None))
```

## Actual Behavior
The code fails with the following error:

```
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid 'tools': empty array. Expected an array with minimum length 1, but got an empty array instead.", 'type': 'invalid_request_error', 'param': 'tools', 'code': 'empty_array'}}
```

<details>
<summary>Full Stack Trace</summary>

```
Traceback (most recent call last):
  File "/Users/shvets/repos/ai4c/widget_rag_bot/test.py", line 24, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/shvets/repos/ai4c/widget_rag_bot/test.py", line 20, in main
    response = await agent.run("Hello, how are you?")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shvets/repos/ai4c/widget_rag_bot/.venv/lib/python3.11/site-packages/pydantic_ai/agent.py", line 122, in run
    model_response, request_cost = await agent_model.request(messages)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shvets/repos/ai4c/widget_rag_bot/.venv/lib/python3.11/site-packages/pydantic_ai/models/openai.py", line 88, in request
    response = await self.completions_create(messages)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shvets/repos/ai4c/widget_rag_bot/.venv/lib/python3.11/site-packages/pydantic_ai/models/openai.py", line 114, in completions_create
    return await self.client.chat.completions.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shvets/repos/ai4c/widget_rag_bot/.venv/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1661, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/Users/shvets/repos/ai4c/widget_rag_bot/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1839, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shvets/repos/ai4c/widget_rag_bot/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1533, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/shvets/repos/ai4c/widget_rag_bot/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1634, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid 'tools': empty array. Expected an array with minimum length 1, but got an empty array instead.", 'type': 'invalid_request_error', 'param': 'tools', 'code': 'empty_array'}}
```
</details>

## Root Cause
The issue appears to be in the `models/openai.py` file where an empty tools list is being sent to the Azure OpenAI API. The API requires that if a tools parameter is included, it must contain at least one tool.

## Proposed Solution
Modify the `models/openai.py` file to check if the tools list is empty before including it in the API call. If the tools list is empty, omit it from the request parameters.

## Environment
- OS: macOS 15.1.1
- Python: 3.11.9
- pydantic-ai: 0.0.2
- openai: 1.54.4

<details>
<summary>Full Dependencies List</summary>

```
aiohappyeyeballs==2.4.3
aiohttp==3.11.2
aiosignal==1.3.1
annotated-types==0.7.0
anyio==4.6.2.post1
asgiref==3.8.1
asyncio==3.4.3
attrs==24.2.0
backoff==2.2.1
bcrypt==4.2.0
build==1.2.2.post1
cachetools==5.5.0
certifi==2024.8.30
cffi==1.17.1 ; platform_python_implementation != 'PyPy'
charset-normalizer==3.4.0
chroma-hnswlib==0.7.6
chromadb==0.5.18
click==8.1.7
colorama==0.4.6
coloredlogs==15.0.1
cryptography==43.0.3
dataclasses-json==0.6.7
deprecated==1.2.14
distro==1.9.0
docx2txt==0.8
durationpy==0.9
ecdsa==0.19.0
eval-type-backport==0.2.0
fastapi==0.115.5
filelock==3.16.1
flatbuffers==24.3.25
frozenlist==1.5.0
fsspec==2024.10.0
google-auth==2.36.0
googleapis-common-protos==1.66.0
greenlet==3.1.1 ; (python_full_version < '3.13' and platform_machine == 'AMD64') or (python_full_version < '3.13' and platform_machine == 'WIN32') or (python_full_version < '3.13' and platform_machine == 'aarch64') or (python_full_version < '3.13' and platform_machine == 'amd64') or (python_full_version < '3.13' and platform_machine == 'ppc64le') or (python_full_version < '3.13' and platform_machine == 'win32') or (python_full_version < '3.13' and platform_machine == 'x86_64')
griffe==1.5.1
grpcio==1.67.1
h11==0.14.0
httpcore==1.0.6
httptools==0.6.4
httpx==0.27.2
httpx-sse==0.4.0
huggingface-hub==0.26.2
humanfriendly==10.0
idna==3.10
importlib-metadata==8.5.0
importlib-resources==6.4.5
jiter==0.7.1
jose==1.0.0
jsonpatch==1.33
jsonpointer==3.0.0
kubernetes==31.0.0
langchain==0.3.7
langchain-chroma==0.1.4
langchain-community==0.3.7
langchain-core==0.3.18
langchain-openai==0.2.8
langchain-text-splitters==0.3.2
langsmith==0.1.143
logfire-api==2.6.2
markdown-it-py==3.0.0
marshmallow==3.23.1
mdurl==0.1.2
mmh3==5.0.1
monotonic==1.6
mpmath==1.3.0
multidict==6.1.0
mypy-extensions==1.0.0
numpy==1.26.4
oauthlib==3.2.2
onnxruntime==1.20.0
openai==1.54.4
opentelemetry-api==1.28.1
opentelemetry-exporter-otlp-proto-common==1.28.1
opentelemetry-exporter-otlp-proto-grpc==1.28.1
opentelemetry-instrumentation==0.49b1
opentelemetry-instrumentation-asgi==0.49b1
opentelemetry-instrumentation-fastapi==0.49b1
opentelemetry-proto==1.28.1
opentelemetry-sdk==1.28.1
opentelemetry-semantic-conventions==0.49b1
opentelemetry-util-http==0.49b1
orjson==3.10.11
overrides==7.7.0
packaging==24.2
posthog==3.7.0
propcache==0.2.0
protobuf==5.28.3
pyasn1==0.6.1
pyasn1-modules==0.4.1
pycparser==2.22 ; platform_python_implementation != 'PyPy'
pydantic==2.9.2
pydantic-ai==0.0.2
pydantic-core==2.23.4
pydantic-settings==2.6.1
pygments==2.18.0
pypdf==5.1.0
pypika==0.48.9
pyproject-hooks==1.2.0
pyreadline3==3.5.4 ; sys_platform == 'win32'
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-jose==3.3.0
python-multipart==0.0.17
pyyaml==6.0.2
regex==2024.11.6
requests==2.32.3
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
rich==13.9.4
rsa==4.9
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
sqlalchemy==2.0.35
starlette==0.41.2
sympy==1.13.3
tenacity==9.0.0
tiktoken==0.8.0
tokenizers==0.20.3
tqdm==4.67.0
typer==0.13.0
typing-extensions==4.12.2
typing-inspect==0.9.0
urllib3==2.2.3
uvicorn==0.32.0
uvloop==0.21.0 ; platform_python_implementation != 'PyPy' and sys_platform != 'cygwin' and sys_platform != 'win32'
watchfiles==0.24.0
websocket-client==1.8.0
websockets==14.1
wrapt==1.16.0
yarl==1.17.1
zipp==3.21.0
```
</details>

## Additional Notes
The standard Azure OpenAI SDK example works correctly:

```python
import asyncio
from openai import AsyncAzureOpenAI

async def main():
    client = AsyncAzureOpenAI(
        api_key="xxx",
        api_version="2024-06-01",
        azure_endpoint="https://xxx",
    )
    response = await client.chat.completions.create(
        model="gpt-4o", 
        messages=[{"role": "user", "content": "Hello, how are you?"}]
    )
    print(response.model_dump_json(indent=2))

asyncio.run(main())
```

<details>
<summary>Output</summary>

```json
{
  "id": "chatcmpl-AbSujMF1DsjMMJsYB31TggjezCSzb",
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "logprobs": null,
      "message": {
        "content": "Hello! How can I assist you today?",
        "refusal": null,
        "role": "assistant",
        "audio": null,
        "function_call": null,
        "tool_calls": null
      }
    }
  ],
  "created": 1733492645,
  "model": "gpt-4o-2024-08-06",
  "object": "chat.completion",
  "service_tier": null,
  "system_fingerprint": "fp_04751d0b65",
  "usage": {
    "completion_tokens": 9,
    "prompt_tokens": 9,
    "total_tokens": 18,
    "completion_tokens_details": null,
    "prompt_tokens_details": null
  }
}
```
</details>

**Comment by slavashvets** [comment]
Sorry. The problem was actually on my side - `uv add` installed an older version (0.0.2) of pydantic-ai instead of the latest version (0.0.10). After updating to version 0.0.10 the code works as expected.

Closing this issue. Thank you for your time!
