### ISSUE TITLE
IndexError with run_stream and AsyncAzureOpenAI

### ISSUE THREAD

**Issue by celeriev** [pydantic/pydantic-ai#164]
Similar as https://github.com/langchain-ai/langchain/issues/6462

The choices attribute is an empty list in the first chunk when using AsyncAzureOpenAI, hence this [code](https://github.com/pydantic/pydantic-ai/blob/6201af4dc8130aeb9ee81d073bae98d02acdb709/pydantic_ai_slim/pydantic_ai/models/openai.py#L196) throws the following error:
```
Traceback (most recent call last):
  File "/app/app.py", line 312, in on_message
    async with test_agent.run_stream(user_prompt=message.content) as result:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pydantic_ai/agent.py", line 271, in run_stream
    async with agent_model.request_stream(messages) as model_response:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pydantic_ai/models/openai.py", line 139, in request_stream
    yield await self._process_streamed_response(response)
  File "/usr/local/lib/python3.10/site-packages/pydantic_ai/models/openai.py", line 198, in _process_streamed_response
    delta = first_chunk.choices[0].delta
IndexError: list index out of range
```

**Comment by samuelcolvin** [comment]
Thanks for reporting, should be fixable.

**Comment by celeriev** [comment]
Thanks!
