### ISSUE TITLE
Unrecognized request argument supplied: parallel_tool_calls when using Azure Open AI client

### ISSUE THREAD

**Issue by dgl452** [pydantic/pydantic-ai#169]
Hi I did an small modification of the bank support example to use Azure Open AI client but it raises an exception:

```
Traceback (most recent call last):
  File "/home/daniel/repos/test_daniel/demo.py", line 83, in <module>
    result = support_agent.run_sync('What is my balance?', deps=deps)
  File "/home/daniel/repos/test_daniel/venv/lib/python3.10/site-packages/pydantic_ai/agent.py", line 246, in run_sync
    return loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/daniel/repos/test_daniel/venv/lib/python3.10/site-packages/pydantic_ai/agent.py", line 193, in run
    model_response, request_cost = await agent_model.request(messages)
  File "/home/daniel/repos/test_daniel/venv/lib/python3.10/site-packages/pydantic_ai/models/openai.py", line 132, in request
    response = await self._completions_create(messages, False)
  File "/home/daniel/repos/test_daniel/venv/lib/python3.10/site-packages/pydantic_ai/models/openai.py", line 163, in _completions_create
    return await self.client.chat.completions.create(
  File "/home/daniel/repos/test_daniel/venv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1661, in create
    return await self._post(
  File "/home/daniel/repos/test_daniel/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1843, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/home/daniel/repos/test_daniel/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1537, in request
    return await self._request(
  File "/home/daniel/repos/test_daniel/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1638, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': 'Unrecognized request argument supplied: parallel_tool_calls', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

The code to replicate the exception:

```py
from openai import AsyncAzureOpenAI
from pydantic_ai.models.openai import OpenAIModel

from dataclasses import dataclass

from pydantic import BaseModel, Field

from pydantic_ai import Agent, RunContext


class DatabaseConn:
    """This is a fake database for example purposes.

    In reality, you'd be connecting to an external database
    (e.g. PostgreSQL) to get information about customers.
    """

    @classmethod
    async def customer_name(cls, *, id: int) -> str | None:
        if id == 123:
            return 'John'

    @classmethod
    async def customer_balance(cls, *, id: int, include_pending: bool) -> float:
        if id == 123:
            return 123.45
        else:
            raise ValueError('Customer not found')


@dataclass
class SupportDependencies:
    customer_id: int
    db: DatabaseConn


class SupportResult(BaseModel):
    support_advice: str = Field(description='Advice returned to the customer')
    block_card: bool = Field(description='Whether to block their')
    risk: int = Field(description='Risk level of query', ge=0, le=10)


client = AsyncAzureOpenAI(
    azure_endpoint='',
    api_version='2024-07-01-preview',
    api_key='',
    azure_deployment=""
)

model = OpenAIModel('gpt-35-turbo', openai_client=client)

support_agent = Agent(
    model=model,
    deps_type=SupportDependencies,
    result_type=SupportResult,
    system_prompt=(
        'You are a support agent in our bank, give the '
        'customer support and judge the risk level of their query. '
        "Reply using the customer's name."
    ),
)


@support_agent.system_prompt
async def add_customer_name(ctx: RunContext[SupportDependencies]) -> str:
    customer_name = await ctx.deps.db.customer_name(id=ctx.deps.customer_id)
    return f"The customer's name is {customer_name!r}"


@support_agent.tool
async def customer_balance(
    ctx: RunContext[SupportDependencies], include_pending: bool
) -> str:
    """Returns the customer's current account balance."""
    balance = await ctx.deps.db.customer_balance(
        id=ctx.deps.customer_id,
        include_pending=include_pending,
    )
    return f'${balance:.2f}'


deps = SupportDependencies(customer_id=123, db=DatabaseConn())
result = support_agent.run_sync('What is my balance?', deps=deps)
print(result.data)
"""
support_advice='Hello John, your current account balance, including pending transactions, is $123.45.' block_card=False
risk=1
"""

result = support_agent.run_sync('I just lost my card!', deps=deps)
print(result.data)
"""
support_advice="I'm sorry to hear that, John. We are temporarily blocking your card to prevent unauthorized transactions
." block_card=True risk=8
"""
```

**Comment by samuelcolvin** [comment]
Looks like this is discussed at length in https://github.com/Azure/azure-rest-api-specs/issues/29545.

Happy to accept a PR to add `enable_parallel_tool_calls: bool = True` kwarg to `OpenAIModel` which you can set to `False` when using `AsyncAzureOpenAI` until they fix it.

**Comment by sydney-runkle** [comment]
Fixed by https://github.com/pydantic/pydantic-ai/pull/750, you can now set `parallel_tool_calls` in `ModelSettings` :)

**Comment by Dirt-Nasty** [comment]
I'm not sure #750 actually fixes the issue.  Even when specified to False in ModelSettings its passes it as False to the serving endpoint.  We need a way to completely override that field and not send it in to the endpoint at all.

**Comment by sydney-runkle** [comment]
@Dirt-Nasty,

I don't think I understand your point - could you please provide more detail?

**Comment by Dirt-Nasty** [comment]
Sure @sydney-runkle 

The issue posted is that `parallel_tool_calls` is not supported on models hosted on Azure.

The changes that recently when in with #750 allow you to control that argument via `ModelSettings` but its still being passed in.

When using Azure as a model we need a way to completely remove that kwarg from being passed.

I've tested this by locally modifying the pydantic-ai OpenAI client by commenting out `parallel_tool_calls` from being passed.

#750 gave the flexibility to control the value via `ModelSettings` but we need a way to complete exclude that argument from being sent all together.

With my modification I can use Azure hosted models.

```python
async def _completions_create(
        self, messages: list[ModelMessage], stream: bool, model_settings: ModelSettings | None
    ) -> chat.ChatCompletion | AsyncStream[ChatCompletionChunk]:
        # standalone function to make it easier to override
        if not self.tools:
            tool_choice: Literal['none', 'required', 'auto'] | None = None
        elif not self.allow_text_result:
            tool_choice = 'required'
        else:
            tool_choice = 'auto'

        openai_messages = list(chain(*(self._map_message(m) for m in messages)))

        model_settings = model_settings or {}

        return await self.client.chat.completions.create(
            model=self.model_name,
            messages=openai_messages,
            n=1,
            #parallel_tool_calls=model_settings.get('parallel_tool_calls', True if self.tools else NOT_GIVEN),
            tools=self.tools or NOT_GIVEN,
            tool_choice=tool_choice or NOT_GIVEN,
            stream=stream,
            stream_options={'include_usage': True} if stream else NOT_GIVEN,
            max_tokens=model_settings.get('max_tokens', NOT_GIVEN),
            temperature=model_settings.get('temperature', NOT_GIVEN),
            top_p=model_settings.get('top_p', NOT_GIVEN),
            timeout=model_settings.get('timeout', NOT_GIVEN),
        )
```
