### ISSUE TITLE
Support/Documentation for Agent handoffs

### ISSUE THREAD

**Issue by Bradley-Butcher** [pydantic/pydantic-ai#219]
Hey! I'm a big fan of the framework so far. Is there a plan for agent handoffs? For example, in the demo library OpenAI released, [swarm](https://github.com/openai/swarm):

```
def transfer_to_agent_b():
    return agent_b


agent_a = Agent(
    name="Agent A",
    instructions="You are a helpful agent.",
    functions=[transfer_to_agent_b],
)
```

Is there some intended pattern for this? I think this could work, though I'm yet to try it

```
@agent_a.tool
async def transfer_to_agent_b(ctx: RunContext[HypothesisDeps]):
    return await ctx.deps.agent_b.run(...)
```

I am excited to hear your plans for multi-agent functionality. It helps when you've got too many tools to cram into a single agent.

p.s. If I missed some page in the documentation on this then I apologize!

**Comment by samuelcolvin** [comment]
Hey @Bradley-Butcher 

```py
@agent_a.tool
async def transfer_to_agent_b(ctx: RunContext[HypothesisDeps]):
    return await ctx.deps.agent_b.run(...)
```

Is exactly what I'd suggest, it just needs documenting. This might overlap with #120.

**Comment by jonathanbouchet** [comment]
inspired by the example of https://github.com/pydantic/pydantic-ai/issues/120

```py
@dataclass
class Deps:
    agent_add: Agent
    agent_writer: Agent

class PoemModel(BaseModel):
    """the model returned by the agent

    :param _type_ BaseModel: _description_
    :return _type_: _description_
    """
    text: str = Field(description="the poem generated by the agent")

class FinalResponse(BaseModel):
    """the final answer of the query

    :param _type_ BaseModel: _description_
    :return _type_: _description_
    """
    output: str | PoemModel

agent = Agent(
    model,
    system_prompt="""
    You are a helpful assistant. 
    Reroute to the appropriate agent based on the user's query.
    """,
    result_type=FinalResponse)

writer_agent = Agent(
    model, 
    system_prompt="Write about a given topic.",
    result_type=PoemModel)

add_agent = Agent(
    model, 
    system_prompt="return the sum of the 2 numbers")

deps = Deps(agent_add=add_agent, agent_writer=writer_agent).data

@agent.tool
def transfer_to_writer_agent(ctx: RunContext, topic: str):
    """
    Ask writer_agent to write a poem about a given topic.
    """
    print(f"topic for poem: {topic}")
    result = ctx.deps.agent_writer.run_sync(f"Write a poem about {topic}.")
    return result

@agent.tool
def transfer_to_math_agent(ctx: RunContext, a: int, b: int) -> str:
    """
    Ask add_agent to add 2 numbers
    """
    print(f"numbers to add: {a}, {b}")
    result = ctx.deps.agent_add.run_sync(f"add {a} and {b}").data
    return result
```

- initially both agent had a `string` output but I wanted to add a pydantic response for the `writer_agent` for testing purposes.
   - I didn't get the main agent to return the `Poem` model so it explains why the main agent can either return a `string` or `Poem` model now

1.  checking the writer_agent returns the correct type
```py
r0 = writer_agent.run_sync(user_prompt="write a poem in 1 verse about Pydantic ?")

# 21:32:00.516 writer_agent run prompt=write a poem in 1 verse about Pydantic ?
# 21:32:00.518   preparing model and tools run_step=1
# 21:32:00.519   model request
# 21:32:02.183   handle model response

r0.data
# PoemModel(text="In the realm of Python's embrace, Pydantic reigns with graceful pace, \nData models, pure and bright, \nValidation dances in the light.")
```

2.  running both tests
```py
result = agent.run_sync("what is the sum of 2 and 2 equal to ?", deps=deps)
# 21:44:29.366 agent run prompt=what is the sum of 2 and 2 equal to ?
# 21:44:29.367   preparing model and tools run_step=1
# 21:44:29.368   model request
# 21:44:30.151   handle model response
# 21:44:30.154     running tools=['transfer_to_math_agent']
# 21:44:31.061   preparing model and tools run_step=2
# 21:44:31.062   model request
# 21:44:32.494   handle model response

print(f"{result.data}, {type(result.data)}")
# output='The sum of 2 and 2 is 4.', <class '__main__.FinalResponse'>

result = agent.run_sync("write a poem about quantum physics in 1 verse of 3 lines", deps=deps)
# 21:51:56.415 agent run prompt=write a poem about quantum physics in 1 verse of 3 lines
# 21:51:56.416   preparing model and tools run_step=1
# 21:51:56.417   model request
# 21:51:57.025   handle model response
# 21:51:57.026     running tools=['transfer_to_writer_agent']
# 21:52:01.735   preparing model and tools run_step=2
# 21:52:01.736   model request
# 21:52:03.369   handle model response

print(f"{result.data}, {type(result.data)}")
# output='In whispers of the cosmic dance,  \nWhere particles in shadows prance,  \nA world unseen, so strange yet bright.', <class '__main__.FinalResponse'>
```

- we can see from the logs that the routing seems to work
- when routing for the `writer_agent`, I was expecting to be a `Poem` class , so I might have messed with the output formats within the different agents here

**Comment by jonathanbouchet** [comment]
- quick update: defining a pydantic model for both agents works
- also now both tool return the `response.data` directly

```py
class MathModel(BaseModel):
    """the model returned by the math agent

    :param _type_ BaseModel: _description_
    :return _type_: _description_
    """
    val: int = Field(description="the result of the operation")

class PoemModel(BaseModel):
    """the model returned by the writer agent

    :param _type_ BaseModel: _description_
    :return _type_: _description_
    """
    text: str = Field(description="the poem generated by the agent")

class FinalResponse(BaseModel):
    """the final answer of the query

    :param _type_ BaseModel: _description_
    :return _type_: _description_
    """
    output: MathModel | PoemModel = Field(description="the final answer of the query")

[...]
@agent.tool
def transfer_to_writer_agent(ctx: RunContext, topic: str):
    """
    Ask writer_agent to write a poem about a given topic.
    """
    print(f"topic for poem: {topic}")
    result = ctx.deps.agent_writer.run_sync(f"Write a poem about {topic}.").data
    return result

@agent.tool
def transfer_to_math_agent(ctx: RunContext, a: int, b: int):
    """
    Ask add_agent to add 2 numbers
    """
    print(f"numbers to add: {a}, {b}")
    result = ctx.deps.agent_add.run_sync(f"add {a} and {b}").data
    return result
```

```py
result = agent.run_sync("what is the sum of 3 and 3 equal to ?", deps=deps)
print(f"{result.data}, {type(result.data)}")
# output=MathModel(val=6), <class '__main__.FinalResponse'>

print(f"{result.data.output.val}, {type(result.data.output.val)}")
# 6, <class 'int'>

result = agent.run_sync("write a poem about quantum physics in 1 verse of 3 lines", deps=deps)
print(f"{result.data}, {type(result.data)}")
# output=PoemModel(text='In realms where particles dance and play,\nWhere the fabric of time stretches thin,\nWhispers of secrets in particles sway.'), <class '__main__.FinalResponse'>

print(f"{result.data.output.text}, {type(result.data.output.text)}")
# In the realm where particles play,  
# Dancing shadows in a quantum ballet,  
# Tiny whispers of uncertainty reign., <class 'str'>
```

**Comment by pietz** [comment]
@jonathanbouchet thank you for this example but unless I'm missing something, it's not the solution to OPs problem. Neither is @samuelcolvin suggestion. You might get away with it in a simple example like this, but I don't think it will work on realistic examples that need to scale.

In both examples, we're basically just using another agent to run a single prediction step. It's not a handover like in true multi-agent systems. Try implementing the still very simple [Triage Agent](https://github.com/openai/swarm/tree/main/examples/triage_agent) example from Swarm. I don't think it will work without ugly workarounds.

That's why Swarm introduces the notion of a `Client` that is always connected to one `Agent` instance, which might change during runtime.

Happy to be wrong though!

**Comment by sydney-runkle** [comment]
I believe we can mark this as resolved by https://ai.pydantic.dev/multi-agent-applications/ for now :)

**Comment by someshfengde** [comment]
can we use directly `await agent.run()` instead of `agent.run_sync()` when I tried it gave me error as 

 !  ◰³ .venv  ~/D/c/decision_helper   *…  uv run python decision_maker.py                                    31.1s  Sun Feb  9 19:26:42 2025
13:59:17.936 entry_and_info_gathering run prompt=I want to create AI project which people will use?.
13:59:17.956   preparing model request params run_step=1
13:59:17.957   model request
Logfire project URL: https://logfire.pydantic.dev/somesh/decision-maker
13:59:20.334   handle model response
13:59:20.336     running tools=['get_more_info_from_user']

    -----
    Please answer the following questions
    -----
    ['What specific problem do you want your AI project to solve?', 'Who is your target audience or users for this project?', 'What features or 
functionalities do you envision for this AI project?', 'Do you have any specific technologies or platforms in mind to develop this project?', 
'What is your timeframe or deadline for launching this project?']
    -----
    : AGI , 1 billion users, all the funcitonality, 5 years with 5 trillion dollers credit line 
13:59:41.271   preparing model request params run_step=2
13:59:41.274   model request
13:59:46.331   handle model response
13:59:46.332     running tools=['transfer_to_pros_agent', 'transfer_to_cons_agent']
Getting pros for: AGI project for 1 billion users
Traceback (most recent call last):
  File "/Users/som/Downloads/code/decision_helper/decision_maker.py", line 183, in <module>
    asyncio.run(main(query = "I want to create AI project which people will use?."))
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/som/Downloads/code/decision_helper/decision_maker.py", line 168, in main
    res =await entry_and_info_gathering.run(query, deps = deps)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/som/Downloads/code/decision_helper/.venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 340, in run
    end_result, _ = await graph.run(
                    ^^^^^^^^^^^^^^^^
  File "/Users/som/Downloads/code/decision_helper/.venv/lib/python3.12/site-packages/pydantic_graph/graph.py", line 187, in run
    next_node = await self.next(next_node, history, state=state, deps=deps, infer_name=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/som/Downloads/code/decision_helper/.venv/lib/python3.12/site-packages/pydantic_graph/graph.py", line 263, in next
    next_node = await node.run(ctx)
                ^^^^^^^^^^^^^^^^^^^
  File "/Users/som/Downloads/code/decision_helper/.venv/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py", line 297, in run
    return await self._handle_tool_calls_response(ctx, tool_calls, handle_span)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/som/Downloads/code/decision_helper/.venv/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py", line 329, in _handle_tool_calls_response
    tool_responses = await _process_function_tools(tool_calls, final_result and final_result.tool_name, ctx)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/som/Downloads/code/decision_helper/.venv/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py", line 650, in _process_function_tools
    task_results: Sequence[_messages.ToolReturnPart | _messages.RetryPromptPart] = await asyncio.gather(*tasks)
                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/som/Downloads/code/decision_helper/.venv/lib/python3.12/site-packages/pydantic_ai/tools.py", line 281, in run
    response_content = await function(*args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/som/Downloads/code/decision_helper/decision_maker.py", line 155, in transfer_to_pros_agent
    result = await ctx.deps.pros_identifier_agent.run_sync(f"Please evaluate the topic and provide pros for this {query} previous agent asked this question to the user {questions} and user provided following answer {answer}.")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/som/Downloads/code/decision_helper/.venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 432, in run_sync
    return asyncio.get_event_loop().run_until_complete(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 662, in run_until_complete
    self._check_running()
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 621, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
sys:1: RuntimeWarning: coroutine 'Agent.run' was never awaited
