### ISSUE TITLE
 Incorrect Class Type for `result` in `result_validator` Callback

### ISSUE THREAD

**Issue by ishswar** [pydantic/pydantic-ai#414]
Incorrect Class Type for `result` in `result_validator` Callback

**Pydantic AI Version:** 0.0.13

---

#### Description:

I am experiencing an issue with the `result_validator` decorator in Pydantic AI when validating the result of a dice game. I expected the `result` parameter in the `validate_result` function to be of type `Game`, but instead, it is of type `pydantic_ai.tools.RunContext`.

Below is the code snippet I am using:

```python
@dice_game_agent.result_validator
def validate_result(result: Game, ctx: RunContext[PlayerData]) -> Game:
    """Validate the result of the dice game."""
    print("Printing class of result")
    print(result.__class__)

    return result
```

**Expected Behavior:**
- I expect the `result` parameter to be an instance of the `Game` model class.

**Actual Behavior:**
- When I run the code, the `result` is incorrectly identified as `pydantic_ai.tools.RunContext`.

**Output:**
```
Printing class of result
<class 'pydantic_ai.tools.RunContext'>
```

#### Steps to Reproduce:
1. Create an agent with a `result_validator` callback like the one above.
2. Pass the `result` and `ctx` parameters as described in the code.
3. Observe the type of `result`, which incorrectly returns `RunContext` instead of the expected `Game` model.

#### Additional Information:
- When I swap the position of `ctx` and `result` in the parameter order (i.e., `ctx` first, then `result`), the issue is resolved, and the `result` is correctly identified as `Game`.

```python
@dice_game_agent.result_validator
def validate_result(ctx: RunContext[PlayerData],result: Game,) -> Game:
    """Validate the result of the dice game."""
    print("Printing class of result")
    print(result.__class__)

    return result
```
#### Output : 

```bash
pydantic_ai version: 0.0.13
Printing class of result
<class '__main__.Game'>
```

- Is this expected behavior, or is this a bug in the way Pydantic AI handles result validation?

---

#### Expected Action:
- Please clarify if this behavior is expected and, if so, document it.
- If it is a bug, It would be good to address it 

### Full Code 

```python
from dataclasses import dataclass
import random
from typing import Optional

import logfire
import pydantic_ai
from devtools import debug
from groq import BaseModel
from pydantic_ai import Agent, RunContext
import dotenv

dotenv.load_dotenv()
# # 'if-token-present' means nothing will be sent (and the example will work) if you don't have logfire configured
# logfire.configure(token='if-token-present')

class GameResult(BaseModel):
    game_result: str

class Game(BaseModel):
    invalid_game_prompt_explanation_message : Optional[str]
    result : Optional[GameResult]


@dataclass
class PlayerData:
    name: str
    guessed_number: int
    recorder_agent: Agent


recorder_agent = Agent(
    'openai:gpt-4o-mini',
    deps_type=PlayerData,
    system_prompt=(
         """
         You record the player's name and the number they guessed.
         """
    ),
)

@recorder_agent.tool
async def record_player_data(ctx: RunContext[PlayerData]) -> str:
    record_str = f"Recorded player {ctx.deps.name} with guess {ctx.deps.guessed_number}."
    print(record_str)
    return record_str

dice_game_agent = Agent(
    'openai:gpt-4o-mini',
    deps_type=PlayerData,
    system_prompt=(
        "You're a dice game, you should roll the die and see if the number "
        "you get back matches the user's guess. If so, tell them they're a winner. "
        "Use the player's name in the response."
        "Always record the player's name and the number data they guessed."
    ),
    result_type=Game,
)

@dice_game_agent.tool
async def record_data(ctx: RunContext[PlayerData]) -> str:
    debug(ctx.messages)
    await ctx.deps.recorder_agent.run(f"Recorded player {ctx.deps.name} with guess {ctx.deps.guessed_number}.",
                                     deps=ctx.deps,
                                     # message_history=ctx.messages
                                     )


@dice_game_agent.tool_plain
async def roll_die() -> str:
    """Roll a six-sided die and return the result."""
    return str(random.randint(1, 6))


@dice_game_agent.tool
async def get_player_name(ctx: RunContext[PlayerData]) -> str:
    """Get the player's name."""
    return ctx.deps.name

@dice_game_agent.result_validator
def validate_result(result: Game, ctx: RunContext[PlayerData]) -> Game:
    """Validate the result of the dice game."""
    print("Printing class of result")
    print(result.__class__)

    return result



def main():
    # Print pydantic_ai's version
    print(f"pydantic_ai version: {pydantic_ai.__version__}")

    player_data = PlayerData(name="Alice", guessed_number=4, recorder_agent=recorder_agent)
    dice_result = dice_game_agent.run_sync(f'This is not a proper request', deps=player_data)

if __name__ == '__main__':
    main()
```

**Comment by samuelcolvin** [comment]
Your function signature is wrong, type checking would point to this.

See [the docs](https://ai.pydantic.dev/results/#result-validators-functions).

Signature should be

```py
def validate_result(ctx: RunContext[PlayerData], result: Game) -> Game:

**Comment by ishswar** [comment]
@samuelcolvin - I know my signature is wrong, but I wanted that to be checked at runtime - as code does this for tools  

This code will fail 

```python
@dice_game_agent.tool
async def get_player_name_fail(prompt: str , ctx: RunContext[PlayerData]) -> str:
    """Get the player's name."""
    return ctx.deps.name
```

For `tool` - RunContext has to be the first argument, and for runtime, we do get an error see below. 

```
Traceback (most recent call last):
  File "pydantic_ai/playground/result_validate.py", line 80, in <module>
    async def get_player_name_fail(prompt: str , ctx: RunContext[PlayerData]) -> str:
  File "miniconda3/envs/pydantic_ai/lib/python3.10/site-packages/pydantic_ai/agent.py", line 672, in tool
    self._register_function(func, True, retries, prepare)
  File "miniconda3/envs/pydantic_ai/lib/python3.10/site-packages/pydantic_ai/agent.py", line 753, in _register_function
    tool = Tool(func, takes_ctx=takes_ctx, max_retries=retries_, prepare=prepare)
  File "miniconda3/envs/pydantic_ai/lib/python3.10/site-packages/pydantic_ai/tools.py", line 207, in __init__
    f = _pydantic.function_schema(function, takes_ctx)
  File "miniconda3/envs/pydantic_ai/lib/python3.10/site-packages/pydantic_ai/_pydantic.py", line 118, in function_schema
    raise UserError(f'Error generating schema for {function.__qualname__}:\n  {error_details}')
pydantic_ai.exceptions.UserError: Error generating schema for get_player_name_fail:
  First parameter of tools that take context must be annotated with RunContext[...]
  RunContext annotations can only be used as the first argument
  ```

So, why not throw the same Error for `result_validator` ? As of version 0.0.13, it does not. 

if we can't I am okay with closing this case
