### ISSUE TITLE
Ollama 0.53 with llama3.2 does not seem to work.

### ISSUE THREAD

**Issue by msharpe-pros** [pydantic/pydantic-ai#437]
Tried both examples listed here https://ai.pydantic.dev/api/models/ollama/

Ollama 0.53
Python: 3.12.7
MacOS: 15.2

Both produce similar errors

```
(.a) 11:53:51 ~/python/pydanticai $> python ollama_example.py
Traceback (most recent call last):
  File "/Users/msharpe/python/pydanticai/ollama_example.py", line 13, in <module>
    result = agent.run_sync('Where were the olympics held in 2012?')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/msharpe/python/pydanticai/.a/lib/python3.12/site-packages/pydantic_ai/agent.py", line 319, in run_sync
    return asyncio.get_event_loop().run_until_complete(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/msharpe/.pyenv/versions/3.12.7/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/msharpe/python/pydanticai/.a/lib/python3.12/site-packages/pydantic_ai/agent.py", line 259, in run
    final_result, tool_responses = await self._handle_model_response(model_response, deps, messages)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/msharpe/python/pydanticai/.a/lib/python3.12/site-packages/pydantic_ai/agent.py", line 852, in _handle_model_response
    return await self._handle_text_response(text, deps, conv_messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/msharpe/python/pydanticai/.a/lib/python3.12/site-packages/pydantic_ai/agent.py", line 872, in _handle_text_response
    self._incr_result_retry()
  File "/Users/msharpe/python/pydanticai/.a/lib/python3.12/site-packages/pydantic_ai/agent.py", line 1054, in _incr_result_retry
    raise exceptions.UnexpectedModelBehavior(
pydantic_ai.exceptions.UnexpectedModelBehavior: Exceeded maximum retries (1) for result validation
```

**Comment by msharpe-pros** [comment]
(.a) 11:58:57 ~/python/pydanticai $> pip list
Package            Version
------------------ -----------
annotated-types    0.7.0
anthropic          0.42.0
anyio              4.7.0
cachetools         5.5.0
certifi            2024.12.14
charset-normalizer 3.4.0
colorama           0.4.6
distro             1.9.0
eval_type_backport 0.2.0
google-auth        2.37.0
griffe             1.5.1
groq               0.13.1
h11                0.14.0
httpcore           1.0.7
httpx              0.27.2
idna               3.10
jiter              0.8.2
json_repair        0.31.0
jsonpath-python    1.0.6
logfire-api        2.7.1
mistralai          1.2.5
mypy-extensions    1.0.0
openai             1.58.1
pip                24.3.1
pyasn1             0.6.1
pyasn1_modules     0.4.1
pydantic           2.10.3
pydantic-ai        0.0.13
pydantic-ai-slim   0.0.13
pydantic_core      2.27.1
python-dateutil    2.9.0.post0
requests           2.32.3
rsa                4.9
six                1.17.0
sniffio            1.3.1
tqdm               4.67.1
typing_extensions  4.12.2
typing-inspect     0.9.0
urllib3            2.2.3

**Comment by bbkgh** [comment]
I think it's a regression to be fixed. This problem doesn't exist in pydantic-ai 0.0.12.

**Comment by samuelcolvin** [comment]
Please use proper markdown to format the exception as code so I can read it!

**Comment by samuelcolvin** [comment]
thanks for reporting, yup I see the problem

if I run
```py
from pydantic import BaseModel

from pydantic_ai import Agent
from devtools import debug


class CityLocation(BaseModel):
    city: str
    country: str


agent = Agent('ollama:llama3.2', result_type=CityLocation)

try:
    result = agent.run_sync('Where were the olympics held in 2012?')
except Exception:
    debug(agent.last_run_messages)
    raise
print(result.data)
print(result.cost())
```

I get:

```py
ollama_example.py:16 <module>
    agent.last_run_messages: [
        ModelRequest(
            parts=[
                UserPromptPart(
                    content='Where were the olympics held in 2012?',
                    timestamp=datetime.datetime(2024, 12, 18, 13, 16, 24, 48314, tzinfo=datetime.timezone.utc),
                    part_kind='user-prompt',
                ),
            ],
            kind='request',
        ),
        ModelResponse(
            parts=[
                TextPart(
                    content='',
                    part_kind='text',
                ),
                ToolCallPart(
                    tool_name='final_result',
                    args=ArgsJson(
                        args_json='{"city":"London","country":"United Kingdom"}',
                    ),
                    tool_call_id='call_b66c3djp',
                    part_kind='tool-call',
                ),
            ],
            timestamp=datetime.datetime(2024, 12, 18, 13, 16, 24, tzinfo=datetime.timezone.utc),
            kind='response',
        ),
        ModelRequest(
            parts=[
                RetryPromptPart(
                    content='Plain text responses are not permitted, please call one of the functions instead.',
                    tool_name=None,
                    tool_call_id=None,
                    timestamp=datetime.datetime(2024, 12, 18, 13, 16, 24, 589070, tzinfo=datetime.timezone.utc),
                    part_kind='retry-prompt',
                ),
            ],
            kind='request',
        ),
        ModelResponse(
            parts=[
                TextPart(
                    content='',
                    part_kind='text',
                ),
                ToolCallPart(
                    tool_name='final_result',
                    args=ArgsJson(
                        args_json='{"city":"London","country":"United Kingdom"}',
                    ),
                    tool_call_id='call_7fdv18vk',
                    part_kind='tool-call',
                ),
            ],
            timestamp=datetime.datetime(2024, 12, 18, 13, 16, 25, tzinfo=datetime.timezone.utc),
            kind='response',
        ),
    ] (list) len=4
Traceback (most recent call last):
  File "/Users/samuel/code/pydantic-ai/ollama_example.py", line 14, in <module>
    result = agent.run_sync('Where were the olympics held in 2012?')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/pydantic-ai/pydantic_ai_slim/pydantic_ai/agent.py", line 319, in run_sync
    return asyncio.get_event_loop().run_until_complete(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/.pyenv/versions/3.12.6/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/samuel/code/pydantic-ai/pydantic_ai_slim/pydantic_ai/agent.py", line 259, in run
    final_result, tool_responses = await self._handle_model_response(model_response, deps, messages)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/pydantic-ai/pydantic_ai_slim/pydantic_ai/agent.py", line 852, in _handle_model_response
    return await self._handle_text_response(text, deps, conv_messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/pydantic-ai/pydantic_ai_slim/pydantic_ai/agent.py", line 872, in _handle_text_response
    self._incr_result_retry()
  File "/Users/samuel/code/pydantic-ai/pydantic_ai_slim/pydantic_ai/agent.py", line 1054, in _incr_result_retry
    raise exceptions.UnexpectedModelBehavior(
pydantic_ai.exceptions.UnexpectedModelBehavior: Exceeded maximum retries (1) for result validation
```

The problem is

```py
                TextPart(
                    content='',
                    part_kind='text',
                ),
```

Ollama is returning an empty test part which is meaning pyantic-ai is assuming this is a text response, we should ignore empty text parts.

**Comment by mattwilliamson** [comment]
I still see an issue.

```sh
pip install -U git+https://github.com/pydantic/pydantic-ai.git
```

```python
from pydantic import BaseModel

from pydantic_ai import Agent
from devtools import debug


class CityLocation(BaseModel):
    city: str
    country: str


agent = Agent('ollama:llama3.2', result_type=CityLocation)

try:
    result = agent.run_sync('Where were the olympics held in 2012?')
except Exception:
    debug(agent.last_run_messages)
    raise
print(result.data)
print(result.cost())
```

```sh
    agent.last_run_messages: [
        ModelRequest(
            parts=[
                UserPromptPart(
                    content='Where were the olympics held in 2012?',
                    timestamp=datetime.datetime(2024, 12, 18, 16, 31, 44, 572825, tzinfo=datetime.timezone.utc),
                    part_kind='user-prompt',
                ),
            ],
            kind='request',
        ),
        ModelResponse(
            parts=[
                TextPart(
                    content='',
                    part_kind='text',
                ),
                ToolCallPart(
                    tool_name='final_result',
                    args=ArgsJson(
                        args_json='{"city":"London","country":"United Kingdom"}',
                    ),
                    tool_call_id='call_s5lmuhzg',
                    part_kind='tool-call',
                ),
            ],
            timestamp=datetime.datetime(2024, 12, 18, 16, 31, 46, tzinfo=datetime.timezone.utc),
            kind='response',
        ),
        ModelRequest(
            parts=[
                RetryPromptPart(
                    content='Plain text responses are not permitted, please call one of the functions instead.',
                    tool_name=None,
                    tool_call_id=None,
                    timestamp=datetime.datetime(2024, 12, 18, 16, 31, 46, 177375, tzinfo=datetime.timezone.utc),
                    part_kind='retry-prompt',
                ),
            ],
            kind='request',
        ),
        ModelResponse(
            parts=[
                TextPart(
                    content='',
                    part_kind='text',
                ),
                ToolCallPart(
                    tool_name='final_result',
                    args=ArgsJson(
                        args_json='{"city":"London","country":"United Kingdom"}',
                    ),
                    tool_call_id='call_pdwy4wt1',
                    part_kind='tool-call',
                ),
            ],
            timestamp=datetime.datetime(2024, 12, 18, 16, 31, 46, tzinfo=datetime.timezone.utc),
            kind='response',
        ),
    ] (list) len=4
Traceback (most recent call last):
  File "/home/matt/src/test/story_assistant_test.py", line 15, in <module>
    result = agent.run_sync('Where were the olympics held in 2012?')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/test/lib/python3.12/site-packages/pydantic_ai/agent.py", line 319, in run_sync
    return asyncio.get_event_loop().run_until_complete(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/test/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/test/lib/python3.12/site-packages/pydantic_ai/agent.py", line 259, in run
    final_result, tool_responses = await self._handle_model_response(model_response, deps, messages)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/test/lib/python3.12/site-packages/pydantic_ai/agent.py", line 852, in _handle_model_response
    return await self._handle_text_response(text, deps, conv_messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/test/lib/python3.12/site-packages/pydantic_ai/agent.py", line 872, in _handle_text_response
    self._incr_result_retry()
  File "/home/matt/miniconda3/envs/test/lib/python3.12/site-packages/pydantic_ai/agent.py", line 1054, in _incr_result_retry
    raise exceptions.UnexpectedModelBehavior(
pydantic_ai.exceptions.UnexpectedModelBehavior: Exceeded maximum retries (1) for result validation

```

```sh
>>> import pydantic_ai
>>> pydantic_ai.__version__
'0.0.13'
```

**Comment by gt732** [comment]
same, what is the fix?

**Comment by bgeesaman** [comment]
This example now works for me. Notice the version is `0.0.14`:
```python
import logfire
from pydantic import BaseModel
from pydantic_ai import Agent, __version__
from devtools import debug

logfire.configure(send_to_logfire='if-token-present', console=False)


class CityLocation(BaseModel):
    city: str
    country: str


agent = Agent('ollama:llama3.1:8b-instruct-fp16', result_type=CityLocation)
result = agent.run_sync('Where were the olympics held in 2012?')

print(result.data)
print(result.usage())
print(__version__)
```

```bash
❯ python3 test-ollama.py
city='London' country='United Kingdom'
Usage(requests=1, request_tokens=178, response_tokens=24, total_tokens=202, details=None)
0.0.14
```

**Comment by xindoreen** [comment]
I'm encountering the same error while running the roulette_wheel.py example code from the PydanticAI documentation. The only difference is that I replaced the model with "ollama:llama3.2". The error message is: pydantic_ai.exceptions.UnexpectedModelBehavior: Exceeded maximum retries (1) for result validation.

PydanticAI: 0.0.16

**Comment by youngsoul** [comment]
@xindoreen Same for me.  Running the roulette_wheel.py with the model name change to 'Ollama:llama3.2'.

My dependencies are the following:
dependencies = [
    "ollama>=0.4.5",
    "pydantic-ai>=0.0.16",
    "python-dotenv>=1.0.1",
]

I have the same problem with version 0.0.16, 0.0.14 and 0.0.13

**Comment by xindoreen** [comment]
@youngsoul this thread is closed. But you can check this issue out at #576
