### ISSUE TITLE
`OpenAIStreamTextResponse` breaks when agent tries to use a tool

### ISSUE THREAD

**Issue by lukekh** [pydantic/pydantic-ai#469]
While using `Agent.run_stream` to get a response of type `StreamedRunResult` and using the method `StreamedRunResult .stream_text` with `delta=True` to stream the response, I encounter an error when the agent attempts a tool call.

Here is the stacktrace (with some censoring of filepaths):
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<...>/src/__main__.py", line 48, in <module>
    asyncio.run(streamed_response(user_input))
  File "/Users/work/.pyenv/versions/3.11.4/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/work/.pyenv/versions/3.11.4/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/work/.pyenv/versions/3.11.4/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<...>/src/agents/system.py", line 113, in stream_response
    async for message in response.stream_text(delta=True):
  File "<...>/venv/lib/python3.11/site-packages/pydantic_ai/result.py", line 181, in stream_text
    async for _ in group_iter:
  File "<...>/venv/lib/python3.11/site-packages/pydantic_ai/_utils.py", line 204, in async_iter_groups
    item = done.pop().result()
           ^^^^^^^^^^^^^^^^^^^
  File "<...>/venv/lib/python3.11/site-packages/pydantic_ai/models/openai.py", line 323, in __anext__
    assert choice.delta.content is not None, f'Expected delta with content, invalid chunk: {chunk!r}'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected delta with content, invalid chunk: ChatCompletionChunk(id='chatcmpl-AfoW4ddgsqIMtK9fRp4EsE2mh0W5d', choices=[Choice(delta=ChoiceDelta(content=None, function_call=None, refusal=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_ZK4LQLjd9buO0Zq3NnFRA3WO', function=ChoiceDeltaToolCallFunction(arguments='', name='write_file'), type='function')]), finish_reason=None, index=0, logprobs=None, content_filter_results={})], created=1734528996, model='gpt-4o-2024-05-13', object='chat.completion.chunk', service_tier=None, system_fingerprint='fp_f3927aa00d', usage=None)
```

I believe the error is happening [here](https://github.com/pydantic/pydantic-ai/blob/main/pydantic_ai_slim/pydantic_ai/models/openai.py#L323) and might arise due to the fact that as the agent calls the tool the `choice.delta.content` is `None`, however the `ChatCompletionChunk` has begun making a tool call to the function `'write_file'` as you can see in the stacktrace.

**Comment by samuelcolvin** [comment]
cc @dmontagu.

This should be fixed by #468

**Comment by Akshay090** [comment]
any workarounds that can be done while the fix is merged ?

**Comment by sydney-runkle** [comment]
#468 is merged, marking this as resolved as well 👍
