### ISSUE TITLE
Gemini: Stream text does not work from time to time in conjunction with tools

### ISSUE THREAD

**Issue by alenowak** [pydantic/pydantic-ai#558]
If you use the async streaming text feature together with Gemini and an agent tool it can lead to an exception.
The exception occurs from time to time, not always.
Gemini Pro and Flash are affected.
If you remove the agent tool or use the agent.run_sync() function together with the tool everything seems to work as excepted.

Here is a super simple example to reproduce:

Python 3.12.8
pydantic-ai-slim[vertexai, openai]==0.0.15

```py
import asyncio
from datetime import date

from pydantic_ai import Agent
from pydantic_ai.models.vertexai import VertexAIModel


model = VertexAIModel(
    model_name="gemini-1.5-flash",
    service_account_file=xxx,
    project_id=xxx,
    region=xxx,
)

agent = Agent(model=model)

@agent.tool_plain
def get_current_date() -> str:
    """
    Get the current date.
    Use this function whenever you need to get the current date.

    Returns:
        current_date (str): The current date.
    """
    return date.today().strftime("%d %m %Y")

async def run_agent(user_prompt):
    async with agent.run_stream(user_prompt=user_prompt) as result:
        async for message in result.stream_text(delta=True):
            print(message)

asyncio.run(run_agent(user_prompt="What's the current date?"))
```

Stracktrace:

```
Traceback (most recent call last):
  File "/Users/xxx/xxx/xxx/src/tet.py", line 41, in <module>
    asyncio.run(run_agent(user_prompt="What's the current date?"))
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/src/tet.py", line 37, in run_agent
    async with agent.run_stream(user_prompt=user_prompt) as result:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 408, in run_stream
    async with agent_model.request_stream(messages, model_settings) as model_response:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/pydantic_ai/models/gemini.py", line 183, in request_stream
    async with self._make_request(messages, True, model_settings) as http_response:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/pydantic_ai/models/gemini.py", line 230, in _make_request
    raise exceptions.UnexpectedModelBehavior(f'Unexpected response from gemini {r.status_code}', r.text)
pydantic_ai.exceptions.UnexpectedModelBehavior: Unexpected response from gemini 400, body:
[
  {
    "error": {
      "code": 400,
      "message": "Unable to submit request because it has an empty text parameter. Add a value to the parameter and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini",
      "status": "INVALID_ARGUMENT"
    }
  }
]
```

**Comment by samuelcolvin** [comment]
thanks for reporting, fixed by #568.
