### ISSUE TITLE
You can't use sync call and async streaming in the same application

### ISSUE THREAD

**Issue by alenowak** [pydantic/pydantic-ai#559]
If you use the async streaming text feature together with a sync call in the same application this leads to an exception regarding the event loop.

Python 3.12.8
pydantic-ai-slim[vertexai, openai]==0.0.15

Steps to reproduce:

```
import asyncio

from pydantic_ai import Agent
from pydantic_ai.models.vertexai import VertexAIModel

model = VertexAIModel(
    model_name="gemini-1.5-flash",
    service_account_file=xxx,
    project_id=xxx,
    region=xxx,
)

agent = Agent(model=model)

response = agent.run_sync(user_prompt="Hi")

async def run_agent(user_prompt):
    async with agent.run_stream(user_prompt=user_prompt) as result:
       async for message in result.stream_text(delta=True):
           print(message)

response = asyncio.run(run_agent(user_prompt="Hi"))
```

Exception:

```
Traceback (most recent call last):
  File "/Users/xxx/xxx/xxx/src/tet2.py", line 27, in <module>
    response = asyncio.run(run_agent(user_prompt="Hi"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/src/tet2.py", line 23, in run_agent
    async with agent.run_stream(user_prompt=user_prompt) as result:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 408, in run_stream
    async with agent_model.request_stream(messages, model_settings) as model_response:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/pydantic_ai/models/gemini.py", line 183, in request_stream
    async with self._make_request(messages, True, model_settings) as http_response:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/pydantic_ai/models/gemini.py", line 221, in _make_request
    async with self.http_client.stream(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1583, in stream
    response = await self.send(
               ^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/httpcore/_async/http11.py", line 136, in handle_async_request
    raise exc
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/httpcore/_async/http11.py", line 106, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/httpcore/_async/http11.py", line 177, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/httpcore/_async/http11.py", line 217, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 35, in read
    return await self._stream.receive(max_bytes=max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/anyio/streams/tls.py", line 204, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/anyio/streams/tls.py", line 147, in _call_sslobject_method
    data = await self.transport_stream.receive()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 1289, in receive
    await self._protocol.read_event.wait()
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/asyncio/locks.py", line 209, in wait
    fut = self._get_loop().create_future()
          ^^^^^^^^^^^^^^^^
  File "/Users/xxx/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/asyncio/mixins.py", line 20, in _get_loop
    raise RuntimeError(f'{self!r} is bound to a different event loop')
RuntimeError: <asyncio.locks.Event object at 0x107e104a0 [unset]> is bound to a different event loop
```

**Comment by Ravitwr** [comment]
I was not able to reproduce this issue in Python 3.12.1. It generally should not be a problem unless run_sync is called from within an already-running async function. Internally, run_sync uses something like:

```
return asyncio.get_event_loop().run_until_complete(
    self.run(
        user_prompt,
        message_history=message_history,
        model=model,
        deps=deps,
        model_settings=model_settings,
        usage_limits=usage_limits,
        infer_name=False,
    )
)
```
This creates (and then closes) an event loop for the duration of the sync call. Once that loop closes, running additional async code later is typically fine, so long as you’re not invoking run_sync inside existing async code. You can insert the following snippet between calls to verify whether an event loop is running. Ideally, you should see "No running loop found":
```
try:
    loop = asyncio.get_running_loop()
    print("  Found a running loop:", loop)
except RuntimeError:
    print("  No running loop found")
```

**Comment by alenowak** [comment]
Thanks for your answer and trying to reproduce my issue.
I have tested this issue in Python 3.12.1 as well and recognized the same behavior.
Maybe it's a Mac M1 ARM problem.

I used your code snippet to show if an event loop is running between my two calls but it says: "No running loop found".

But if i insert the code snippet before this line (Pydantic AI code, gemini.py, line 221):

```
File "/Users/xxx/xxx/xxx/.venv/lib/python3.12/site-packages/pydantic_ai/models/gemini.py", line 221, in _make_request
    async with self.http_client.stream(
               ^^^^^^^^^^^^^^^^^^^^^^^^
```
               
it definitely says there is an event loop running: "Found a running loop: <_UnixSelectorEventLoop running=True closed=False debug=False>" and the error seems to happen after this call (see stacktrace).

**Comment by alenowak** [comment]
Maybe it's important to say that I'm using the standalone Python versions of uv or the ones installed by pyenv. I have tested both.

**Comment by basilmontycloud** [comment]
I am using Jupyter notebook and I got this error 

I was able to resolve it by adding this additional package and code.

```PYTHON
import nest_asyncio
nest_asyncio.apply()
```

Here is the explanation of this by Github copilot
```MARKDOWN
The RuntimeError: This event loop is already running occurs because asyncio.run() cannot be called when an event loop is already running, which is common in environments like Jupyter notebooks.

To fix this, you can use nest_asyncio to allow nested use of asyncio.run() or use await directly if you're in an async function.
```


Final code that worked.
```PYTHON
import asyncio
import nest_asyncio # Import package


from pydantic_ai import Agent
from pydantic_ai.models.vertexai import VertexAIModel

nest_asyncio.apply() # Apply nest_asyncio to allow nested event loops



model = VertexAIModel(
    model_name="gemini-1.5-flash",
    service_account_file=xxx,
    project_id=xxx,
    region=xxx,
)

agent = Agent(model=model)

response = agent.run_sync(user_prompt="Hi")

async def run_agent(user_prompt):
    async with agent.run_stream(user_prompt=user_prompt) as result:
       async for message in result.stream_text(delta=True):
           print(message)

response = asyncio.run(run_agent(user_prompt="Hi"))
```

**Comment by muhammedbasilsk** [comment]
I am using Jupyter notebook and I got this error 

I was able to resolve it by adding this additional package and code.

```PYTHON
import nest_asyncio
nest_asyncio.apply()
```
Here is the ref from [pydantic ai](https://ai.pydantic.dev/agents/#introduction)
![image](https://github.com/user-attachments/assets/0d1ea237-0f74-4748-b696-fe8f59c637ef)


Here is the explanation of this by Github copilot
```MARKDOWN
The RuntimeError: This event loop is already running occurs because asyncio.run() cannot be called when an event loop is already running, which is common in environments like Jupyter notebooks.

To fix this, you can use nest_asyncio to allow nested use of asyncio.run() or use await directly if you're in an async function.
```


Final code that worked.
```PYTHON
import asyncio
import nest_asyncio # Import package


from pydantic_ai import Agent
from pydantic_ai.models.vertexai import VertexAIModel

nest_asyncio.apply() # Apply nest_asyncio to allow nested event loops



model = VertexAIModel(
    model_name="gemini-1.5-flash",
    service_account_file=xxx,
    project_id=xxx,
    region=xxx,
)

agent = Agent(model=model)

response = agent.run_sync(user_prompt="Hi")

async def run_agent(user_prompt):
    async with agent.run_stream(user_prompt=user_prompt) as result:
       async for message in result.stream_text(delta=True):
           print(message)

response = asyncio.run(run_agent(user_prompt="Hi"))
```

**Comment by alenowak** [comment]
That is a great workaround for Jupyter Notebooks which i'm using myself.
But i'm pretty unsure if Pydantic AI is working as expected in the area of event loops, sync and asynchronous calls?
